### PR TITLE
Implement slice/1 function required by protocol Enumerable

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by Qqwy** [comment]
Very good!

However, we should probably make this implementation optional, since for certain array implementations there might be a faster implementation possible.

**Comment by eksperimental** [comment]
How do we go about making it optional?

**Comment by Qqwy** [comment]
What I said earlier does not make any sense: The Enumerable implementation is currently not something you get 'for free' as is the case in some of the other collection-based libraries.

For now, this current implementation (which will only be used for ErlangArray and MapArray) is fine. I might try to benchmark other approaches for MapArray at a later point to see if a faster implementation is possible. (For ErlangArray there is no call in `:arrays` that would allow easy slicing so the list conversion is probably the best we can do).

**Comment by eksperimental** [comment]
I will introduce an improvement to the library that will improve performance significantly.

**Pull request merged**
